name: Push to ECR

on:
  push:
    branches: [ "<branch>" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_ACCESS_KEY_SECRET }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: "Amazon ECR Login"
      uses: aws-actions/amazon-ecr-login@v1
    
    - uses: actions/checkout@v2

    - name: "Create .env file"
      run: |
        cat << EOF > .env
        API_HOST=${{ secrets.ENV_API_HOST }}
        EOF

    - name: "Build, tag, and push image to Amazon ECR"
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: nextjs-image
        IMAGE_TAG: ${{ github.sha }}
      run: |
        yarn install
        yarn build
        docker build -t nextjs-image .
        docker tag nextjs-image:latest ${{ secrets.AWS_IAM_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nextjs-image:latest
        docker push ${{ secrets.AWS_IAM_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/nextjs-image:latest
